Repository wmde/fundraising-banners, pull requests merged in 2024-10, with the labels that each got.

#556 C24_WMDE_Mobile_DE_05
  banners/mobile/C24_WMDE_Mobile_DE_05/banner_ctrl.ts
  banners/mobile/C24_WMDE_Mobile_DE_05/banner_var.ts
  banners/mobile/C24_WMDE_Mobile_DE_05/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/components/BannerVar.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/components/FullPageBanner.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/components/FullPageBanner_var.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/components/MiniBanner.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/content/BannerSlides.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/content/BannerText.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/event_map.ts
  banners/mobile/C24_WMDE_Mobile_DE_05/form_items.ts
  banners/mobile/C24_WMDE_Mobile_DE_05/messages.ts
  banners/mobile/C24_WMDE_Mobile_DE_05/styles/Banner.scss
  banners/mobile/C24_WMDE_Mobile_DE_05/styles/FullPageBanner.scss
  banners/mobile/C24_WMDE_Mobile_DE_05/styles/MiniBanner.scss
  banners/mobile/C24_WMDE_Mobile_DE_05/styles/styles.scss
  banners/mobile/C24_WMDE_Mobile_DE_05/styles/styles_var.scss
  campaign_info.toml
  src/components/Icons/HeartIcon.vue
  src/components/ThankYouBox/ThankYouBox.scss
  src/components/ThankYouBox/ThankYouBox.vue
  src/themes/Mikings/ThankYouBox/ThankYouBox.scss
  src/themes/Mikings/swatches/color_light.scss
  test/banners/mobile/components/BannerCtrl.spec.ts
Labels: Currently Live, Approved

#555 C24_WMDE_Desktop_DE_06
  banners/desktop/C24_WMDE_Desktop_DE_06/banner_ctrl.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/banner_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/components/MainBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/content/BannerText.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/content/FallbackSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/content/FallbackText.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/event_map.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/form_items.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/messages.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/Banner.scss
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/FallbackBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/MainBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/MinimisedBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/colors.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/fallback_colors.ts
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/styles.scss
  banners/desktop/C24_WMDE_Desktop_DE_06/styles/styles_var.scss
  campaign_info.toml
  package-lock.json
  src/components/Footer/SmallPrintFooter.scss
  src/components/Footer/SmallPrintFooter.vue
  src/components/Footer/messages/Footer.de.ts
  src/components/Footer/messages/Footer.en.ts
  src/createFAQPageURL.ts
  src/themes/Svingle/Footer/SmallPrintFooter.scss
  src/themes/Svingle/swatches/color_light.scss
  src/themes/Svingle/variables/_breakpoints.scss
  test/banners/desktop/components/BannerCtrl.spec.ts
  test/components/Footer/SmallPrintFooter.spec.ts
Labels: Currently Live, Approved

#563 Inline UoF infographics and Icons into Fundraising Banners
  banners/desktop/C24_WMDE_Desktop_DE_00/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_00/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_00/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_01/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_01/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_02/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_02/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_02/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_03/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_03/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_04/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_04/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_05/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_05/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_05/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_06/components/FallbackBanner.vue
  banners/english/C24_WMDE_Desktop_EN_00/components/BannerCtrl.vue
  banners/english/C24_WMDE_Desktop_EN_00/components/BannerVar.vue
  banners/english/C24_WMDE_Desktop_EN_00/components/FallbackBanner.vue
  banners/english/C24_WMDE_Desktop_EN_01/components/BannerCtrl.vue
  banners/english/C24_WMDE_Desktop_EN_01/components/BannerVar.vue
  banners/english/C24_WMDE_Desktop_EN_01/components/FallbackBanner.vue
  banners/mobile/C24_WMDE_Mobile_DE_00/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_00/components/BannerVar.vue
  banners/mobile/C24_WMDE_Mobile_DE_01/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_01/components/BannerVar.vue
  banners/mobile/C24_WMDE_Mobile_DE_02/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_02/components/BannerVar.vue
  banners/mobile/C24_WMDE_Mobile_DE_03/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_04/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_04/components/BannerVar.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_05/components/BannerVar.vue
  banners/mobile_english/C24_WMDE_Mobile_EN_00/components/BannerCtrl.vue
  banners/mobile_english/C24_WMDE_Mobile_EN_00/components/BannerVar.vue
  banners/pad/C24_WMDE_iPad_00/components/BannerCtrl.vue
  banners/pad/C24_WMDE_iPad_00/components/BannerVar.vue
  banners/wpde_desktop/C24_WPDE_Desktop_00/components/BannerCtrl.vue
  banners/wpde_desktop/C24_WPDE_Desktop_00/components/BannerVar.vue
  banners/wpde_mobile/C24_WPDE_Mobile_00/components/BannerCtrl.vue
  banners/wpde_mobile/C24_WPDE_Mobile_00/components/BannerVar.vue
  src/components/UseOfFunds/FundsContent.vue
  src/components/UseOfFunds/FundsModal.vue
  src/components/UseOfFunds/Icons/IconClose.vue
  src/components/UseOfFunds/Infographics/WMDEFundsForwardingDE.vue
  src/components/UseOfFunds/Infographics/WMDEFundsForwardingEN.vue
  src/themes/UseOfFunds/FundsContent.scss
  src/themes/UseOfFunds/swatches/skin_default.scss
  src/themes/UseOfFunds/swatches/skin_vector-2022.scss
Labels: Ready for review

#572 C24_WMDE_Desktop_EN_02 (round 1)
  banners/english/C24_WMDE_Desktop_EN_02/banner_ctrl.ts
  banners/english/C24_WMDE_Desktop_EN_02/banner_var.ts
  banners/english/C24_WMDE_Desktop_EN_02/components/BannerCtrl.vue
  banners/english/C24_WMDE_Desktop_EN_02/components/BannerVar.vue
  banners/english/C24_WMDE_Desktop_EN_02/components/FallbackBanner.vue
  banners/english/C24_WMDE_Desktop_EN_02/components/MainBanner.vue
  banners/english/C24_WMDE_Desktop_EN_02/content/BannerSlides.vue
  banners/english/C24_WMDE_Desktop_EN_02/content/BannerSlides_var.vue
  banners/english/C24_WMDE_Desktop_EN_02/content/BannerText.vue
  banners/english/C24_WMDE_Desktop_EN_02/content/BannerText_var.vue
  banners/english/C24_WMDE_Desktop_EN_02/content/FallbackSlides.vue
  banners/english/C24_WMDE_Desktop_EN_02/content/FallbackText.vue
  banners/english/C24_WMDE_Desktop_EN_02/event_map.ts
  banners/english/C24_WMDE_Desktop_EN_02/form_items.ts
  banners/english/C24_WMDE_Desktop_EN_02/messages.ts
  banners/english/C24_WMDE_Desktop_EN_02/styles/Banner.scss
  banners/english/C24_WMDE_Desktop_EN_02/styles/FallbackBanner.scss
  banners/english/C24_WMDE_Desktop_EN_02/styles/MainBanner.scss
  banners/english/C24_WMDE_Desktop_EN_02/styles/styles.scss
  campaign_info.toml
  package-lock.json
  test/banners/english/components/BannerCtrl.spec.ts
  test/banners/english/components/FallbackBanner.spec.ts
Labels: Currently Live, Approved

#571 C24_WPDE_Desktop_01
  banners/wpde_desktop/C24_WPDE_Desktop_01/banner_ctrl.ts
  banners/wpde_desktop/C24_WPDE_Desktop_01/banner_var.ts
  banners/wpde_desktop/C24_WPDE_Desktop_01/components/BannerCtrl.vue
  banners/wpde_desktop/C24_WPDE_Desktop_01/components/BannerVar.vue
  banners/wpde_desktop/C24_WPDE_Desktop_01/components/MainBanner.vue
  banners/wpde_desktop/C24_WPDE_Desktop_01/content/BannerSlides.vue
  banners/wpde_desktop/C24_WPDE_Desktop_01/content/BannerText.vue
  banners/wpde_desktop/C24_WPDE_Desktop_01/event_map.ts
  banners/wpde_desktop/C24_WPDE_Desktop_01/form_items.ts
  banners/wpde_desktop/C24_WPDE_Desktop_01/messages.ts
  banners/wpde_desktop/C24_WPDE_Desktop_01/styles/Banner.scss
  banners/wpde_desktop/C24_WPDE_Desktop_01/styles/MainBanner.scss
  banners/wpde_desktop/C24_WPDE_Desktop_01/styles/styles.scss
  banners/wpde_desktop/C24_WPDE_Desktop_01/styles/styles_var.scss
  campaign_info.toml
  docs/2025PostCampaignCleanUp.md
  package-lock.json
  src/components/DonationForm/Forms/MainDonationFormTransactionFees.vue
  src/components/DonationForm/Forms/UpgradeToYearlyButtonForm.vue
  src/components/DonationForm/Forms/UpgradeToYearlyForm.vue
  src/components/DonationForm/MultiStepDonation.vue
  src/components/DonationForm/SubComponents/SubmitValues.vue
  src/components/DonationForm/SubComponents/TransactionFees.scss
  src/components/Footer/FooterAlreadyDonated.vue
  src/components/SetWPDECookieImage/SetAlreadyDonatedCookieImage.vue
  src/components/composables/useFormModel.ts
  src/domain/CloseChoices.ts
  src/environment/dev/CampaignParameterOverride.ts
  src/themes/Treedip/DonationForm/BubbleForm/radio-input.scss
  src/themes/Treedip/DonationForm/SubComponents/TransactionFees.scss
  src/themes/Treedip/DonationForm/SubComponents/radio-input.scss
  src/themes/Treedip/ProgressBar/ProgressBar.scss
  src/themes/Treedip/swatches/color_dark.scss
  src/themes/Treedip/swatches/color_light.scss
  src/themes/Treedip/swatches/skin_default.scss
  src/tracking/events/ClickAlreadyDonatedEvent.ts
  src/tracking/events/CoverTransactionFeesEvent.ts
  src/utils/FormModel/FormModel.ts
  test/banners/wpde_desktop/C24_WPDE_Desktop_01/components/BannerCtrl.spec.ts
  test/banners/wpde_desktop/C24_WPDE_Desktop_01/components/BannerVar.spec.ts
  test/components/Footer/FooterAlreadyDonated.spec.ts
  test/components/composables/useFormModel.spec.ts
  test/features/AlreadyDonatedModal.ts
  test/features/SetCookieImage.ts
  test/features/forms/MainDonation_TransactionFee.ts
  test/features/forms/subForms/MainDonationForm.ts
  test/resetFormModel.ts
  vitest.config.mjs
Labels: Approved, for campaign start

#592 C24_WMDE_Mobile_DE_06
  banners/mobile/C24_WMDE_Mobile_DE_06/banner_ctrl.ts
  banners/mobile/C24_WMDE_Mobile_DE_06/banner_var.ts
  banners/mobile/C24_WMDE_Mobile_DE_06/components/BannerCtrl.vue
  banners/mobile/C24_WMDE_Mobile_DE_06/components/BannerVar.vue
  banners/mobile/C24_WMDE_Mobile_DE_06/components/FullPageBanner.vue
  banners/mobile/C24_WMDE_Mobile_DE_06/components/MiniBanner.vue
  banners/mobile/C24_WMDE_Mobile_DE_06/content/BannerSlides.vue
  banners/mobile/C24_WMDE_Mobile_DE_06/content/BannerText.vue
  banners/mobile/C24_WMDE_Mobile_DE_06/event_map.ts
  banners/mobile/C24_WMDE_Mobile_DE_06/form_items.ts
  banners/mobile/C24_WMDE_Mobile_DE_06/messages.ts
  banners/mobile/C24_WMDE_Mobile_DE_06/messages_var.ts
  banners/mobile/C24_WMDE_Mobile_DE_06/styles/Banner.scss
  banners/mobile/C24_WMDE_Mobile_DE_06/styles/FullPageBanner.scss
  banners/mobile/C24_WMDE_Mobile_DE_06/styles/MiniBanner.scss
  banners/mobile/C24_WMDE_Mobile_DE_06/styles/styles.scss
  banners/mobile/C24_WMDE_Mobile_DE_06/styles/styles_var.scss
  campaign_info.toml
  src/components/DonationForm/MultiStepDonation.vue
  src/page/PageWPORG.ts
  src/themes/Mikings/SoftClose/SoftClose.scss
  src/themes/Mikings/swatches/color_light.scss
  src/themes/Mikings/swatches/skin_default.scss
  src/tracking/events/BannerSubmitOnReturnEvent.ts
  src/utils/LocalCloseTracker.ts
  test/banners/mobile/C24_WMDE_Mobile_DE_06/components/BannerCtrl.spec.ts
  test/banners/mobile/C24_WMDE_Mobile_DE_06/components/BannerVar.spec.ts
  test/components/DonationForm/MultiStepDonation.spec.ts
  test/features/SoftCloseMobile.ts
  test/features/SoftCloseSubmitTracking.ts
Labels: Approved, for campaign start

#599 Expose average donation to banner content
  banners/desktop/C24_WMDE_Desktop_DE_07/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_07/content/BannerSlidesVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_07/content/BannerText.vue
  banners/desktop/C24_WMDE_Desktop_DE_07/content/BannerTextVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_08/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_08/content/BannerText.vue
  docs/2025PostCampaignCleanUp.md
  src/utils/DynamicContent/DynamicCampaignText.ts
  src/utils/DynamicContent/DynamicContent.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_08/components/BannerCtrl.spec.ts
  test/banners/dynamicCampaignContent.ts
  test/banners/english/C24_WMDE_Desktop_EN_02b/components/BannerCtrl.spec.ts
  test/components/ProgressBar/DoubleProgressBar.spec.ts
  test/components/ProgressBar/ProgressBar.spec.ts
  test/features/BannerContent.ts
  test/unit/utils/DynamicContent/DynamicCampaignText.spec.ts
Labels: rebase-needed

#573 C24_WPDE_Mobile_01
  banners/wpde_mobile/C24_WPDE_Mobile_01/FormController.ts
  banners/wpde_mobile/C24_WPDE_Mobile_01/banner_ctrl.ts
  banners/wpde_mobile/C24_WPDE_Mobile_01/banner_var.ts
  banners/wpde_mobile/C24_WPDE_Mobile_01/components/BannerCtrl.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/components/BannerVar.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/components/FullPageBanner.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/components/MiniBanner.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/components/MiniBannerVar.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/content/BannerSlides.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/content/BannerSlidesVar.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/content/BannerText.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/content/BannerTextVar.vue
  banners/wpde_mobile/C24_WPDE_Mobile_01/event_map.ts
  banners/wpde_mobile/C24_WPDE_Mobile_01/form_items.ts
  banners/wpde_mobile/C24_WPDE_Mobile_01/messages.ts
  banners/wpde_mobile/C24_WPDE_Mobile_01/styles/Banner.scss
  banners/wpde_mobile/C24_WPDE_Mobile_01/styles/FullPageBanner.scss
  banners/wpde_mobile/C24_WPDE_Mobile_01/styles/MiniBanner.scss
  banners/wpde_mobile/C24_WPDE_Mobile_01/styles/styles.scss
  campaign_info.toml
  src/components/SetWPDECookieImage/SetAlreadyDonatedCookieImage.vue
  test/banners/wpde_mobile/components/BannerCtrl.spec.ts
  test/banners/wpde_mobile/components/BannerVar.spec.ts
  test/features/SetCookieImageMobile.ts
Labels: for campaign start
