Repository wmde/fundraising-banners, pull requests merged in 2024-12, with the labels that each got.

#644 C24_WMDE_Desktop_DE_18
  banners/desktop/C24_WMDE_Desktop_DE_18/banner_ctrl.ts
  banners/desktop/C24_WMDE_Desktop_DE_18/banner_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_18/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/components/MainBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/content/BannerText.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/content/BannerTitle.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/content/FallbackSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/content/FallbackText.vue
  banners/desktop/C24_WMDE_Desktop_DE_18/event_map.ts
  banners/desktop/C24_WMDE_Desktop_DE_18/form_items.ts
  banners/desktop/C24_WMDE_Desktop_DE_18/messages.ts
  banners/desktop/C24_WMDE_Desktop_DE_18/messages_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_18/styles/Banner.scss
  banners/desktop/C24_WMDE_Desktop_DE_18/styles/FallbackBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_18/styles/MainBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_18/styles/styles.scss
  campaign_info.toml
  test/banners/desktop/C24_WMDE_Desktop_DE_18/components/BannerCtrl.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_18/components/BannerVar.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_18/components/FallbackBanner.spec.ts
Labels: Currently Live

#649 C24_WMDE_Desktop_DE_19
  banners/desktop/C24_WMDE_Desktop_DE_19/banner_ctrl.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/banner_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/components/MainBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/components/MainBannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/content/BannerText.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/content/BannerTitle.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/content/FallbackSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/content/FallbackText.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/content/TenGoodReasonsSticker.vue
  banners/desktop/C24_WMDE_Desktop_DE_19/event_map.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/event_map_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/form_items.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/messages.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/messages_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_19/styles/Banner.scss
  banners/desktop/C24_WMDE_Desktop_DE_19/styles/FallbackBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_19/styles/MainBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_19/styles/MainBannerVar.scss
  banners/desktop/C24_WMDE_Desktop_DE_19/styles/styles.scss
  banners/desktop/C24_WMDE_Desktop_DE_19/styles/styles_var.scss
  campaign_info.toml
  dashboard/wpde-offline/index.html
  src/components/ReasonsToDonate/styles/ReasonsToDonate.scss
  src/themes/Fijitiv/ProgressBar/ProgressBar.scss
  src/themes/Treedip/swatches/color_light.scss
  test/banners/desktop/C24_WMDE_Desktop_DE_19/components/BannerCtrl.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_19/components/BannerVar.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_19/components/FallbackBanner.spec.ts
  test/features/ReasonsToDonate.ts
Labels: Currently Live

#658 C24_WMDE_Desktop_DE_20
  banners/desktop/C24_WMDE_Desktop_DE_20/banner_ctrl.ts
  banners/desktop/C24_WMDE_Desktop_DE_20/banner_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_20/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/components/FallbackBannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/components/MainBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/components/MainBannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/content/BannerText.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/content/BannerTitle.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/content/FallbackSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/content/FallbackText.vue
  banners/desktop/C24_WMDE_Desktop_DE_20/event_map.ts
  banners/desktop/C24_WMDE_Desktop_DE_20/form_items.ts
  banners/desktop/C24_WMDE_Desktop_DE_20/messages.ts
  banners/desktop/C24_WMDE_Desktop_DE_20/messages_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/Banner.scss
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/FallbackBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/FallbackBannerVar.scss
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/MainBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/MainBannerVar.scss
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/styles.scss
  banners/desktop/C24_WMDE_Desktop_DE_20/styles/styles_var.scss
  campaign_info.toml
  docs/2025PostCampaignCleanUp.md
  src/themes/Fijitiv/FallbackBanner/LargeFooter.scss
  test/banners/desktop/C24_WMDE_Desktop_DE_20/components/BannerCtrl.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_20/components/BannerVar.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_20/components/FallbackBanner.spec.ts
  test/features/ReasonsToDonate.ts
Labels: Currently Live

#662 C24_WMDE_Desktop_DE_21
  banners/desktop/C24_WMDE_Desktop_DE_21/banner_ctrl.ts
  banners/desktop/C24_WMDE_Desktop_DE_21/banner_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_21/components/BannerCtrl.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/components/BannerVar.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/components/FallbackBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/components/MainBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/components/MinimisedBanner.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/content/BannerSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/content/BannerText.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/content/BannerTitle.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/content/FallbackSlides.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/content/FallbackText.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/content/MinimisedText.vue
  banners/desktop/C24_WMDE_Desktop_DE_21/event_map.ts
  banners/desktop/C24_WMDE_Desktop_DE_21/event_map_var.ts
  banners/desktop/C24_WMDE_Desktop_DE_21/form_items.ts
  banners/desktop/C24_WMDE_Desktop_DE_21/messages.ts
  banners/desktop/C24_WMDE_Desktop_DE_21/styles/Banner.scss
  banners/desktop/C24_WMDE_Desktop_DE_21/styles/FallbackBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_21/styles/MainBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_21/styles/MinimisedBanner.scss
  banners/desktop/C24_WMDE_Desktop_DE_21/styles/styles.scss
  banners/desktop/C24_WMDE_Desktop_DE_21/styles/styles_var.scss
  banners/desktop/C24_WMDE_Desktop_DE_21/useScrollMinimiser.ts
  campaign_info.toml
  src/components/FallbackBanner/UseOfFundsLink.vue
  src/components/Footer/BannerFooter.vue
  src/components/Footer/FooterAlreadyDonated.vue
  src/components/Footer/messages/Footer.de.ts
  src/components/Footer/messages/Footer.en.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_21/components/BannerCtrl.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_21/components/BannerVar.spec.ts
  test/banners/desktop/C24_WMDE_Desktop_DE_21/components/FallbackBanner.spec.ts
  test/features/AutoCollapseDesktop.ts
  test/features/SoftCloseDesktop.ts
Labels: Currently Live, Ready for review

#676 Fix backwards broken tests
  test/features/ReasonsToDonate.ts
Labels: Ready for review
